In [1]:
print("Numpy")

Numpy


In [2]:
import numpy as np
array=np.array([1,2,3,4,5])
print("1D array:",array)

1D array: [1 2 3 4 5]


In [13]:
#creating 2D array
array_2d=np.array([[21,2,3],[4,5,6]]) #List of List
print("2D array:\n",array_2d)

2D array:
 [[21  2  3]
 [ 4  5  6]]


In [17]:
#creating a 2d array of zeros
zeros_array=np.zeros((3,4)) # 3 rows AND 4 columns
print("Array of zeros:\n",zeros_array)

Array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
# creating a 1d array of one
ones_array=np.ones(5)
print("Array of ones:",ones_array)

Array of ones: [1. 1. 1. 1. 1.]


In [20]:
#Creating an array with value from 0to9
range_array=np.arange(10)
print("Range array:",range_array)

Range array: [0 1 2 3 4 5 6 7 8 9]


In [21]:
#creating an array with 5 evenly spaced values btn 0 and 1
linespace_array=np.linspace(0,1,5) # start,end,nuumber of space btn 0 and 1
print("linespace_array:",linespace_array)

linespace_array: [0.   0.25 0.5  0.75 1.  ]


In [22]:
print("shape of array:",array_2d.shape) #Gives number of rows and columns
print("size of array:",array_2d.size)

shape of array: (2, 3)
size of array: 6


In [23]:
print("Data type of array_2d",array_2d.dtype)

Data type of array_2d int64


In [28]:
#Indexing and slicing
array_1d=np.array([10,20,30,40,50])
print("Element at index 2:",array_1d[2])


Element at index 2: 30


In [30]:
print("Element at last index:",array_1d[-1])

Element at last index: 50


In [2]:
array_2d=np.array([[10,20,30],[40,50,60]])
print("Element at (0,2) :",array_2d[0,2])
print("Element at (01,2) :",array_2d[1,2])

NameError: name 'np' is not defined

In [37]:
print("Second row:",array_2d[1])

Second row: [40 50 60]


In [38]:
print("First column:",array_2d[:,0])

First column: [10 40]


In [39]:
print("second column:",array_2d[:,1])

second column: [20 50]


In [40]:
#Boolean indexing to select elements greater than 30
boolean_index=array_2d[array_2d>30]
print("Elements greater then 30:",boolean_index)

Elements greater then 30: [40 50 60]


In [1]:
print("Elements at indices 0 and 2 of first row:",array_2d[0,[1,2]])

NameError: name 'array_2d' is not defined

In [45]:
#Slicing
slice_1d=array_1d[1:4]
print("Sliced array:",slice_1d)# print btn 1 and 3

Sliced array: [20 30 40]


In [46]:
slice_step_1d=array_1d[0:5:2]
print("sliced array:", slice_step_1d)

sliced array: [10 30 50]


In [49]:
array_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
slice_2d=array_2d[:2,:2] #first check full length and then checks into the list
print("sliced 2d array:",slice_2d)

sliced 2d array: [[10 20]
 [40 50]]


In [51]:
#slicing the first two row
rows_2d=array_2d[:2]
print("First two rows:\n",rows_2d)
last_cloumn_2d=array_2d[:,-1]
print("Last cloumn:\n",last_cloumn_2d)

First two rows:
 [[10 20 30]
 [40 50 60]]
Last cloumn:
 [30 60 90]
